### ISSUE TITLE
SwellRT does not work with phantomjs

### ISSUE THREAD

**Issue by atd** [P2Pvalue/swellrt#156] opened 2016-05-18 10:55 UTC
This is the output of the console:

![image](https://cloud.githubusercontent.com/assets/26228/15356153/6186efa4-1cf7-11e6-8a8c-dfc18ff2ce83.png)

Steps to reproduce

* Download http://phantomjs.org/
* Create `test.js`
```
var page = require('webpage').create();

page.onResourceError = function(resourceError) {
      console.error(resourceError.url + ': ' + resourceError.errorString);
};

page.open('http://swellrt.org', function(status) {
    console.log("Status: " + status);
});
```
* Run `phantomjs --ignore-ssl-errors=yes  --remote-debugger-port=9000 --remote-debugger-autorun=yes test.js`
* Debug in `localhost:9000`

**Comment by pablojan** [comment] 2016-05-19 07:54
mmm it's strange. I can't reproduce from my laptop. I followed the steps and it seems ok. I edited some text in a separated window of swellrt.org and I saw  atmosphere's callback messages  in the phamtomjs console.

Could you check your network env?

![captura de pantalla de 2016-05-19 09 50 51](https://cloud.githubusercontent.com/assets/4454927/15386308/60445db0-1da7-11e6-95da-9fc935c7ae74.png)

**Comment by atd** [comment] 2016-05-19 08:29
I tested it both in local and the prerender's docker 

What version of phantomjs are you using?

`phantomjs -v`

**Comment by pablojan** [comment] 2016-05-19 08:34
Latest from the website

![captura de pantalla de 2016-05-19 10 33 02](https://cloud.githubusercontent.com/assets/4454927/15387382/1eed25da-1dad-11e6-88ec-83730bd68091.png)

**Comment by atd** [comment] 2016-05-19 08:50
Ok, it seems to be related with phantomjs 1.9.8, which was the one I had and the one is distributed in https://github.com/cerisier/docker-prerender

Feel free to close the bug if you don't have interest in investigating it further

**Comment by pablojan** [comment] 2016-05-19 09:01
Ok, I close the issue. Consider to reopen it if you find more issues after upgrading phantomjs.
Thanks

**Closed by pablojan** 2016-05-19 09:01 UTC
